name: AccessGuard
version: 1.0
author: 1Chickxn
main: me.chickxn.paper.PaperPlugin
api-version: 1.20
commands:
  accessguard:
    aliases:
      - aguard
      - accessg
      - perms
      - perm
      - permission